on: push

name: Build and deploy Node app on GCP

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install express
        npm run build --if-present
        npm run test --if-present
        
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
    - run: gcloud info  
        
   # - name: authorize-gcloud
   #   uses: actions/gcloud/auth@master
   #   env:
   #     GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        
   # - name: 'GCP App Deploy'
   #   uses: "actions/gcloud/cli@master"
   #   with:
   #     args: "app deploy --project=twilight-pulsar-46"
